### ISSUE TITLE
Nette integration

### ISSUE THREAD

**Issue by marten-cz** [ataccama/keycloak-adapter-php#4]
Do you have example how the custom Auth class can look like? Just to have the nette user using the keycloak token. I think it will make sense to have it as part of the repository as default implementation.

**Comment by martinjinda** [comment]
We use it with Nette, you can load in BasePresenter or Trait.

```
/** @var Ataccama\Auth\Auth @inject */
public $auth;

public function startup()
{
            parent::startup();
          
            $this->auth->setState($this->storeRequest());

            $this->template->loginUrl = $this->auth->getLoginUrl();

            // waiting for authorization code from Keycloak
            if ($this->auth->authorize($this->getParameter('code'))) {
                $this->redirectUrl($this->auth->getRedirectUri());
            }
}
```

**Comment by marten-cz** [comment]
For logged user, do you create Nette\Security\IIdentity to have the ACL as well, or you are handling that differently?

**Comment by martinjinda** [comment]
@marten-cz We manage roles in Keycloak and simple load them to UserIdentity.
